version: '3.9'
  
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  back:
    build: ./backend 
    env_file: ./backend/.env
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
  front:
    build: ./front/core
    command: sh -c "npm run dev"
    volumes:
      - ./front/core:/front
      - /front/node_modules
      - /front/.next
    ports:
      - "3000:3000"

